### ISSUE TITLE
Add additional Naming Conventions checking rules

### ISSUE THREAD

**Issue by mindaugasrukas** [ongr-io/ongr-strict-standard#35]
* Prefix abstract classes with Abstract. Please note some early Symfony classes do not follow this convention and have not been renamed for backward compatibility reasons. However all new abstract classes must follow this naming convention;
* Suffix interfaces with Interface;
* Suffix traits with Trait;
* Suffix exceptions with Exception;

**Comment by tautrimas** [comment]
I looked around, and it seems, that a lot of frameworks follow this convention strictly.  Even [fig standards themselves](https://github.com/php-fig/fig-standards/blob/e3c16a261db27a2f8a49f0d2d4a5b744e817bd6b/bylaws/002-psr-naming-conventions.md).

This means, that we should investigate, how many breaks it will introduce. Specifically the `Abstract` naming, since we occasionally use `Base*`.

**Comment by saimaz** [comment]
+1

**Comment by saimaz** [comment]
Related https://github.com/ongr-io/ElasticsearchBundle/issues/121

**Comment by saimaz** [comment]
Implemented in #65, Please wait when strict standard will be refactored and then merge it.
